### PR TITLE
Upgrade to support mip installation

### PR DESCRIPTION
**Pull request by ThinkTransit**
Hi Martin,

This PR adds support for installation via the new micropython package manager mip.

You can test this pr using my fork using the following commands

**From REPL**
>>> import mip
>>> mip.install("github:ThinkTransit/uota" version="mip-upgrade")

**From mpremote**
mpremote mip install github:ThinkTransit/uota@mip-upgrade

### CODE REVIEW

**Comment by mkomon** [comment]
Hi Patrick,

thank you for this PR and for showing me what's required of packages to support mip. I will implement the same for other packages of mine (ucertpin, uasn1, uberserk).

I was able to test your patch (after creating the branch in my repo since the links in your fork point at it) and it works well. I will keep this PR open until 1.20 is released and merge it right after that. That should prevent any confusion about "import mip" not working in stable builds.

I notice that you upgraded uota into a proper package (with __init__.py). I don't think that is necessary and in my opinion the package can be distributed as a single file only. Many other MicroPython packages are installed that way and the additional directory hierarchy and __init__.py don't seem to be adding anything. I've tested the simplified package format in commit [f5b7e6d](https://github.com/mkomon/uota/commit/f5b7e6d074267db5134c169bf99052bdebfce104) and it seems to be working as well. What do you think about this approach?

**Comment by ThinkTransit** [comment]
Hi Martin,

Thanks yes that makes sense, I'm sure V1.20 will be released in the near future.

That is interesting, I didn't know it could work in that way. For some reason I thought it had to be a package, that was the only reason I converted it. Agree that single file is better, I will be converting my projects from packages back to single file!

Patrick

**Comment by mkomon** [comment]
It seems to be pretty flexible and you can cherry pick any files (including .mpy) to be placed in the `/lib` directory. Furthermore, github repos can be referenced in deps like below which is awesome (just tested it). I love this, thanks for showing it to me.

```text
"deps": [
      ["github:mkomon/uasn1", "mip-upgrade"]
    ],
```

Now that I am adding this to other packages I think I'll merge this PR right away and just add a note in the docs that the installation using mip requires 1.20 or a nightly.

**Comment by ThinkTransit** [comment]
Yes it's very cool. I actually think mip has been backported to version 1.19 in the stable builds so probably not a big issue to merge now.

I believe that this system will also be linked into the manifest.py system so it will be possible to freeze packages from github directly into the firmware which is very handy.

**Pull request merged**
